version: "3.9"
services:
  api:
    image: iigor93/flask-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /home/deploy/flask-app/docker_config.py:/code/config.py


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /home/deploy/flask-app/data:/var/lib/postgresql